Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -69,7 +69,7 @@ jobs:
                   -e KC_DB_URL=jdbc:postgresql://postgres:5432/${{ secrets.DB_DATABASE }} \
                   -e KC_DB_USERNAME=${{ secrets.DB_USER }} \
                   -e KC_DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
-                   ${{ env.DOCKER_HUB_REPO }}:${{ env.IMAGE_TAG }}
+                   ${{ env.DOCKER_HUB_REPO }}:${{ env.IMAGE_TAG }} start
     - name: Setup SSH key
       run: |
             mkdir -p ~/.ssh
@@ -77,22 +77,17 @@ jobs:
             chmod 600 ~/.ssh/server_key
  
           
-    - name: Wait for Keycloak to be ready
-      run: |
-          for i in {1..60}; do
-          if curl -sSf "http://${{ secrets.SERVER_HOST }}:8081/health/ready"; then
-          echo "Keycloak is up"
-          exit 0
-          fi
-          echo "Waiting for Keycloak... ($i/60)"
-          ssh -o StrictHostKeyChecking=no \
-          -i ~/.ssh/server_key \
-           ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
-           "docker logs keycloak --tail 50 2>/dev/null || true"
-           sleep 10
+            for i in {1..120}; do
+            if curl -sSf "http://${{ secrets.SERVER_HOST }}:8081/health/ready"; then
+            echo "Keycloak is up"
+            exit 0
+            fi
+            echo "Waiting for Keycloak... ($i/120)"
+            ssh -o StrictHostKeyChecking=no -i ~/.ssh/server_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker logs keycloak --tail 50 2>/dev/null || true"
+            sleep 5
             done
-           echo "Keycloak failed to start within timeout"
-           exit 1
+            echo "Keycloak failed to start within timeout"
+            exit 1
  
 
     - name: Configure Keycloak realms and clients
