Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -82,14 +82,14 @@ jobs:
            echo "Checking Keycloak health (attempt $i)..."
            if ssh -o StrictHostKeyChecking=no -i ~/.ssh/server_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            curl -v -H 'Host: ${{ secrets.SERVER_HOST }}:8182' http://${{ secrets.SERVER_HOST }}:8182/auth/health then
-            echo "Keycloak is up"
-            exit 0
-            fi
-             echo "Waiting for Keycloak... ($i/60)"
-            sleep 10  
-            done
-            echo "Keycloak failed to start within timeout"
-            exit 1
+           echo "Keycloak is up"
+           exit 0
+           fi
+           echo "Waiting for Keycloak... ($i/60)"
+           sleep 10  
+           done
+           echo "Keycloak failed to start within timeout"
+           exit 1
 
    
 
