Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -78,18 +78,19 @@ jobs:
 
     - name: Wait for Keycloak to be ready
       run: |
-            for i in {1..60}; do
-            echo "Checking Keycloak health (attempt $i)..."
-            if ssh -o StrictHostKeyChecking=no -i ~/.ssh/server_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
-            "curl -v -H 'Host: ${{ secrets.SERVER_DEV_SUBDOMAIN }}:8182' http://${{ secrets.SERVER_DEV_SUBDOMAIN }}:8182/health"; then
-            echo "Keycloak is up"
-            exit 0
-            fi
-            echo "Waiting for Keycloak... ($i/60)"
-            sleep 10
-            done
-            echo "Keycloak failed to start within timeout"
-            exit 1
+           for i in {1..60}; do  
+           echo "Checking Keycloak health (attempt $i)..."
+           if ssh -o StrictHostKeyChecking=no -i ~/.ssh/server_key ***@*** \
+           curl -v -H 'Host: ***:8182' http://***:8182/auth/health; then
+           echo "Keycloak is up"
+           exit 0
+           fi
+           echo "Waiting for Keycloak... ($i/60)"
+           sleep 10  
+           done
+           echo "Keycloak failed to start within timeout"
+           exit 1
+            
            
          
 
